import { describe, expect, it, vi } from "vitest";
import { BillingService } from "../electron/services/billing-service";
import { OrderService } from "../electron/services/order-service";
import { ShiftService } from "../electron/services/shift-service";
import { createMigratedTestDatabase, seedAuthFixture, seedPhase2Fixture } from "./test-helpers";
vi.mock("electron",()=>({app:{isPackaged:false,getPath:()=>process.cwd(),getVersion:()=>"0.1.0"}}));
describe("phase 3 billing",()=>{
 it("requires a shift and settles a cash bill",()=>{const db=createMigratedTestDatabase();const f=seedAuthFixture(db);seedPhase2Fixture(db);const orders=new OrderService(db);const billing=new BillingService(db);const shift=new ShiftService(db);let order=orders.createDraft("takeaway",{userUuid:f.user.uuid,terminalUuid:f.terminal.uuid});const product=db.prepare("SELECT uuid FROM products ORDER BY id LIMIT 1").get() as {uuid:string};order=orders.addItem({orderUuid:order.uuid,productUuid:product.uuid});expect(()=>billing.settle(order.uuid,[{mode:"cash",amountMinor:order.totals.grandTotalMinor}],{userUuid:f.user.uuid,terminalUuid:f.terminal.uuid})).toThrowError("Open a cashier shift");shift.open(f.terminal.uuid,f.user.uuid,100000);const bill=billing.settle(order.uuid,[{mode:"cash",amountMinor:order.totals.grandTotalMinor,receivedMinor:order.totals.grandTotalMinor+1000}],{userUuid:f.user.uuid,terminalUuid:f.terminal.uuid});expect(bill.status).toBe("settled");expect(bill.balanceMinor).toBe(0);expect(bill.payments[0].changeMinor).toBe(1000);expect(orders.listRunning()).toHaveLength(0);db.close();});
 it("supports exact split payment",()=>{const db=createMigratedTestDatabase();const f=seedAuthFixture(db);seedPhase2Fixture(db);const orders=new OrderService(db);const billing=new BillingService(db);new ShiftService(db).open(f.terminal.uuid,f.user.uuid,0);let order=orders.createDraft("takeaway",{userUuid:f.user.uuid,terminalUuid:f.terminal.uuid});const product=db.prepare("SELECT uuid FROM products ORDER BY id LIMIT 1").get() as {uuid:string};order=orders.addItem({orderUuid:order.uuid,productUuid:product.uuid});const first=Math.floor(order.totals.grandTotalMinor/2);const bill=billing.settle(order.uuid,[{mode:"upi",amountMinor:first},{mode:"card",amountMinor:order.totals.grandTotalMinor-first}],{userUuid:f.user.uuid,terminalUuid:f.terminal.uuid});expect(bill.payments).toHaveLength(2);expect(bill.paidMinor).toBe(order.totals.grandTotalMinor);db.close();});
});
