import { useEffect, useMemo, useState } from "react";
import type { CrmDashboard } from "../../../shared/contracts/crm-contracts";
import { Button } from "../../components/ui/Button";
import { requirePosApi } from "../../utils/pos-api";
import { formatCurrency } from "../../utils/money";

export function CrmScreen(){
 const [data,setData]=useState<CrmDashboard|null>(null);const [error,setError]=useState<string|null>(null);const [customerUuid,setCustomerUuid]=useState("");const [amount,setAmount]=useState("100");const [reason,setReason]=useState("Manual adjustment");const [type,setType]=useState<"points"|"wallet">("points");const [direction,setDirection]=useState<"credit"|"debit">("credit");const [couponCode,setCouponCode]=useState("");const [couponName,setCouponName]=useState("");const [discountValue,setDiscountValue]=useState("10");
 const load=async()=>{const r=await requirePosApi().crm.dashboard();if(r.success){setData(r.data);setError(null);if(!customerUuid&&r.data.accounts[0])setCustomerUuid(r.data.accounts[0].customerUuid);}else setError(r.error.message);};
 useEffect(()=>{void load();},[]);
 const selected=useMemo(()=>data?.accounts.find(a=>a.customerUuid===customerUuid),[data,customerUuid]);
 const adjust=async()=>{const n=Number(amount);if(!customerUuid||!Number.isInteger(n)||n<=0)return;const r=await requirePosApi().crm.adjust({customerUuid,transactionType:type,direction,amount:n,reason});if(r.success)await load();else setError(r.error.message);};
 const saveCoupon=async()=>{const n=Number(discountValue);if(!couponCode.trim()||!couponName.trim()||!Number.isInteger(n)||n<=0)return;const r=await requirePosApi().crm.saveCoupon({code:couponCode,name:couponName,discountType:"percentage",discountValue:n,isActive:true});if(r.success){setCouponCode("");setCouponName("");await load();}else setError(r.error.message);};
 return <div className="space-y-4">
  <header className="rounded-lg border border-app-border bg-white p-4"><h1 className="text-xl font-extrabold">CRM & Loyalty</h1><p className="text-sm text-app-subtle">Manage points, customer wallet, coupons and memberships offline.</p></header>
  {error&&<div className="rounded-md bg-red-50 p-3 text-sm text-red-700">{error}</div>}
  <div className="grid gap-4 xl:grid-cols-[minmax(0,1.4fr)_minmax(340px,0.6fr)]">
   <section className="rounded-lg border border-app-border bg-white"><div className="border-b border-app-border p-4 font-bold">Customer balances</div><div className="max-h-[460px] overflow-y-auto divide-y divide-app-border">{data?.accounts.map(a=><button key={a.customerUuid} onClick={()=>setCustomerUuid(a.customerUuid)} className={`flex w-full items-center justify-between p-4 text-left ${customerUuid===a.customerUuid?"bg-[#eef7f5]":"hover:bg-app-muted"}`}><div><div className="font-bold">{a.customerName}</div><div className="text-xs text-app-subtle">{a.phone||"No phone"} · {a.tier}</div></div><div className="text-right"><div className="font-bold">{a.pointsBalance} pts</div><div className="text-sm text-app-subtle">{formatCurrency(a.walletMinor)}</div></div></button>)}</div></section>
   <section className="space-y-4"><div className="rounded-lg border border-app-border bg-white p-4"><h2 className="font-extrabold">Balance adjustment</h2><p className="mt-1 text-sm text-app-subtle">{selected?.customerName||"Select a customer"}</p><div className="mt-3 grid grid-cols-2 gap-2"><select value={type} onChange={e=>setType(e.target.value as typeof type)} className="h-11 rounded-md border border-app-border px-3"><option value="points">Points</option><option value="wallet">Wallet (minor units)</option></select><select value={direction} onChange={e=>setDirection(e.target.value as typeof direction)} className="h-11 rounded-md border border-app-border px-3"><option value="credit">Credit</option><option value="debit">Debit</option></select></div><input value={amount} onChange={e=>setAmount(e.target.value)} className="mt-2 h-11 w-full rounded-md border border-app-border px-3" placeholder="Amount"/><input value={reason} onChange={e=>setReason(e.target.value)} className="mt-2 h-11 w-full rounded-md border border-app-border px-3" placeholder="Reason"/><Button className="mt-3 w-full" onClick={()=>void adjust()}>Apply Adjustment</Button></div>
   <div className="rounded-lg border border-app-border bg-white p-4"><h2 className="font-extrabold">Quick coupon</h2><input value={couponCode} onChange={e=>setCouponCode(e.target.value.toUpperCase())} className="mt-3 h-11 w-full rounded-md border border-app-border px-3" placeholder="Code e.g. SAVE10"/><input value={couponName} onChange={e=>setCouponName(e.target.value)} className="mt-2 h-11 w-full rounded-md border border-app-border px-3" placeholder="Coupon name"/><div className="mt-2 flex gap-2"><input value={discountValue} onChange={e=>setDiscountValue(e.target.value)} className="h-11 min-w-0 flex-1 rounded-md border border-app-border px-3" placeholder="Percent"/><Button onClick={()=>void saveCoupon()}>Save</Button></div></div></section>
  </div>
  <section className="rounded-lg border border-app-border bg-white"><div className="border-b border-app-border p-4 font-bold">Coupons</div><div className="grid gap-3 p-4 md:grid-cols-2 xl:grid-cols-3">{data?.coupons.map(c=><div key={c.uuid} className="rounded-md border border-app-border p-3"><div className="flex justify-between"><span className="font-extrabold">{c.code}</span><span className="text-xs text-app-subtle">{c.isActive?"Active":"Inactive"}</span></div><div className="mt-1 text-sm">{c.name}</div><div className="mt-2 font-bold">{c.discountType==="percentage"?`${c.discountValue}%`:formatCurrency(c.discountValue)}</div></div>)}{!data?.coupons.length&&<div className="text-sm text-app-subtle">No coupons created.</div>}</div></section>
 </div>;
}
