import { useEffect, useState } from "react";
import type { OnlineDashboard, OnlineOrder } from "../../../shared/contracts/online-contracts";
import type { FloorMap } from "../../../shared/contracts/table-contracts";
import { Button } from "../../components/ui/Button";
import { requirePosApi } from "../../utils/pos-api";
import { formatCurrency } from "../../utils/money";

export function OnlineOrdersScreen(){
 const [data,setData]=useState<OnlineDashboard|null>(null);const [floor,setFloor]=useState<FloorMap|null>(null);const [error,setError]=useState<string|null>(null);const [channelName,setChannelName]=useState("MealHi5 Online");const [customer,setCustomer]=useState("Demo Online Customer");const [item,setItem]=useState("Online Burger");const [price,setPrice]=useState("25000");
 const load=async()=>{const [d,t]=await Promise.all([requirePosApi().online.dashboard(),requirePosApi().tables.getFloorMap()]);if(d.success){setData(d.data);setError(null);}else setError(d.error.message);if(t.success)setFloor(t.data);};useEffect(()=>{void load();},[]);
 const saveChannel=async()=>{const r=await requirePosApi().online.saveChannel({name:channelName,channelType:"mealhi5",isActive:true,autoAccept:false});if(r.success)await load();else setError(r.error.message);};
 const createDemo=async()=>{const n=Number(price);if(!item.trim()||!customer.trim()||!Number.isInteger(n)||n<0)return;const r=await requirePosApi().online.createOrder({channelUuid:data?.channels[0]?.uuid??null,orderType:"takeaway",customerName:customer,paymentStatus:"cod",items:[{itemName:item,qty:1,unitPriceMinor:n}]});if(r.success)await load();else setError(r.error.message);};
 const status=async(order:OnlineOrder,next:OnlineOrder["status"])=>{const r=await requirePosApi().online.updateStatus({orderUuid:order.uuid,status:next});if(r.success)await load();else setError(r.error.message);};
 const generateQr=async(tableUuid:string)=>{const r=await requirePosApi().online.generateQr({tableUuid});if(r.success)await load();else setError(r.error.message);};
 return <div className="space-y-4"><header className="flex items-center justify-between rounded-lg border border-app-border bg-white p-4"><div><h1 className="text-xl font-extrabold">Online & QR Orders</h1><p className="text-sm text-app-subtle">Local intake foundation for MealHi5, website and table QR orders.</p></div><div className="rounded-full bg-amber-50 px-3 py-1 text-sm font-bold text-amber-700">{data?.pendingCount??0} pending</div></header>{error&&<div className="rounded-md bg-red-50 p-3 text-sm text-red-700">{error}</div>}
 <div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_360px]"><section className="rounded-lg border border-app-border bg-white"><div className="border-b border-app-border p-4 font-bold">Order queue</div><div className="max-h-[600px] overflow-y-auto divide-y divide-app-border">{data?.orders.map(o=><div key={o.uuid} className="p-4"><div className="flex items-start justify-between gap-3"><div><div className="font-extrabold">{o.customerName} · {o.orderType.replace("_"," ")}</div><div className="text-xs text-app-subtle">{o.channelName||"Direct"} · {new Date(o.receivedAt).toLocaleString()}</div></div><div className="text-right"><div className="font-bold">{formatCurrency(o.grandTotalMinor)}</div><span className="text-xs uppercase text-app-subtle">{o.status}</span></div></div><div className="mt-2 text-sm">{o.items.map(i=>`${i.qty}× ${i.itemName}`).join(", ")}</div><div className="mt-3 flex flex-wrap gap-2">{o.status==="pending"&&<><Button onClick={()=>void status(o,"accepted")}>Accept</Button><Button variant="danger" onClick={()=>void status(o,"rejected")}>Reject</Button></>}{o.status==="accepted"&&<Button onClick={()=>void status(o,"preparing")}>Preparing</Button>}{o.status==="preparing"&&<Button onClick={()=>void status(o,"ready")}>Ready</Button>}{o.status==="ready"&&<Button onClick={()=>void status(o,"completed")}>Complete</Button>}</div></div>)}{!data?.orders.length&&<div className="p-8 text-center text-app-subtle">No online orders yet.</div>}</div></section>
 <aside className="space-y-4"><section className="rounded-lg border border-app-border bg-white p-4"><h2 className="font-extrabold">Channel setup</h2><input value={channelName} onChange={e=>setChannelName(e.target.value)} className="mt-3 h-11 w-full rounded-md border border-app-border px-3"/><Button className="mt-2 w-full" onClick={()=>void saveChannel()}>Save Channel</Button></section><section className="rounded-lg border border-app-border bg-white p-4"><h2 className="font-extrabold">Create test order</h2><input value={customer} onChange={e=>setCustomer(e.target.value)} className="mt-3 h-11 w-full rounded-md border border-app-border px-3" placeholder="Customer"/><input value={item} onChange={e=>setItem(e.target.value)} className="mt-2 h-11 w-full rounded-md border border-app-border px-3" placeholder="Item"/><input value={price} onChange={e=>setPrice(e.target.value)} className="mt-2 h-11 w-full rounded-md border border-app-border px-3" placeholder="Price in minor units"/><Button className="mt-2 w-full" onClick={()=>void createDemo()}>Receive Test Order</Button></section></aside></div>
 <section className="rounded-lg border border-app-border bg-white"><div className="border-b border-app-border p-4"><h2 className="font-extrabold">Table QR ordering</h2><p className="text-sm text-app-subtle">Generate one stable ordering token for each table.</p></div><div className="grid gap-3 p-4 md:grid-cols-2 xl:grid-cols-4">{floor?.tables.map(t=>{const token=data?.qrTokens.find(q=>q.tableUuid===t.uuid);return <div key={t.uuid} className="rounded-md border border-app-border p-3"><div className="font-bold">{t.name}</div>{token?<><div className="mt-2 break-all text-xs text-app-subtle">{token.orderingUrl}</div><Button variant="secondary" className="mt-3 w-full" onClick={()=>void generateQr(t.uuid)}>Regenerate</Button></>:<Button className="mt-3 w-full" onClick={()=>void generateQr(t.uuid)}>Generate QR Token</Button>}</div>;})}</div></section>
 </div>;
}
