import { useEffect, useMemo, useState } from "react";
import { useSearchParams } from "react-router-dom";
import { Button } from "../../components/ui/Button";
import { useBillingStore } from "../../stores/billing-store";
import { useShiftStore } from "../../stores/shift-store";
import type { PaymentMode } from "../../../shared/contracts/billing-contracts";
const money=(n:number)=>`₹${(n/100).toFixed(2)}`;
export function BillingScreen(){const [params]=useSearchParams();const orderUuid=params.get("orderUuid")??"";const {bill,loading,error,preview,settle,print}=useBillingStore();const {shift,load}=useShiftStore();const [mode,setMode]=useState<PaymentMode>("cash");const [cashReceived,setCashReceived]=useState("");const [message,setMessage]=useState("");useEffect(()=>{void load();if(orderUuid)void preview(orderUuid);},[orderUuid,load,preview]);const total=bill?.grandTotalMinor??0;const received=Math.round(Number(cashReceived||0)*100);const change=useMemo(()=>Math.max(0,received-total),[received,total]);if(!orderUuid)return <div className="rounded border bg-white p-5">Open Billing from a running order.</div>;return <div className="mx-auto grid max-w-5xl grid-cols-[1fr_360px] gap-4"><section className="rounded-lg border bg-white p-5"><h1 className="text-xl font-extrabold">Bill {bill?.orderNo}</h1><div className="mt-5 space-y-3"><Row label="Subtotal" value={money(bill?.subtotalMinor??0)}/><Row label="Discount" value={`-${money(bill?.discountMinor??0)}`}/><Row label="Taxable" value={money(bill?.taxableMinor??0)}/><Row label="GST" value={money(bill?.taxMinor??0)}/><Row label="Grand total" value={money(total)} strong/></div>{bill?.status==="settled"&&<div className="mt-5 rounded bg-green-50 p-3 font-bold text-green-700">Payment complete</div>}</section><aside className="rounded-lg border bg-white p-5"><h2 className="font-bold">Payment</h2>{!shift&&<div className="mt-3 rounded bg-amber-50 p-3 text-sm text-amber-800">Open a cashier shift before settlement.</div>}<div className="mt-4 grid grid-cols-3 gap-2">{(["cash","upi","card"] as PaymentMode[]).map(x=><button key={x} className={`rounded border p-2 text-sm font-bold uppercase ${mode===x?'border-app-primary bg-app-muted':''}`} onClick={()=>setMode(x)}>{x}</button>)}</div>{mode==="cash"&&<><label className="mt-4 block text-sm">Cash received (₹)</label><input className="mt-1 w-full rounded border p-2" value={cashReceived} onChange={e=>setCashReceived(e.target.value)}/><div className="mt-2 text-sm">Change: <b>{money(change)}</b></div></>}{error&&<div className="mt-3 text-sm text-red-600">{error}</div>}{message&&<div className="mt-3 text-sm text-green-700">{message}</div>}{bill?.status!=="settled"?<Button className="mt-5 w-full" disabled={loading||!shift||(mode==="cash"&&received<total)} onClick={async()=>{const ok=await settle(orderUuid,[{mode,amountMinor:total,receivedMinor:mode==="cash"?received:undefined}]);if(ok)setMessage("Bill settled successfully.");}}>Settle {money(total)}</Button>:<Button className="mt-5 w-full" onClick={async()=>{const r=await print();if(r)setMessage(`${r.copyType} receipt queued.`);}}>Queue Receipt</Button>}</aside></div>}
function Row({label,value,strong=false}:{label:string;value:string;strong?:boolean}){return <div className={`flex justify-between border-b pb-2 ${strong?'text-lg font-extrabold':''}`}><span>{label}</span><span>{value}</span></div>}
