import {useEffect,useState} from "react";
import type {SaveEmployeeInput,StaffDashboard} from "../../../shared/contracts/staff-contracts";
import {Button} from "../../components/ui/Button";
import {requirePosApi} from "../../utils/pos-api";
import {formatCurrency} from "../../utils/money";
type Tab="employees"|"attendance"|"roles"|"payroll"|"audit";
const empty:SaveEmployeeInput={name:"",username:"",password:"",pin:"",systemRole:"waiter",employeeCode:"",department:"",designation:"",salaryType:"monthly",baseSalaryMinor:0,isActive:true};
export function StaffScreen(){
 const[d,setD]=useState<StaffDashboard|null>(null),[tab,setTab]=useState<Tab>("employees"),[f,setF]=useState(empty),[err,setErr]=useState<string|null>(null);
 const load=async()=>{const r=await requirePosApi().staff.dashboard();if(r.success){setD(r.data);setErr(null)}else setErr(r.error.message)};
 useEffect(()=>{void load()},[]);
 const save=async()=>{const r=await requirePosApi().staff.saveEmployee(f);if(r.success){setF(empty);await load()}else setErr(r.error.message)};
 return <div className="space-y-4">
  <section className="flex flex-wrap items-center justify-between gap-3 rounded-lg border bg-white p-4"><div><h1 className="text-xl font-extrabold">Staff, HR & Security</h1><p className="text-sm text-app-subtle">Employees, attendance, roles, payroll and audit logs.</p></div><div className="flex gap-2"><Metric label="Employees" value={String(d?.employees.length??0)}/><Metric label="Present" value={String(d?.presentToday??0)}/><Metric label="Checked In" value={String(d?.openAttendance??0)}/><Button variant="secondary" onClick={()=>void load()}>Refresh</Button></div></section>
  <div className="flex flex-wrap gap-2">{(["employees","attendance","roles","payroll","audit"] as Tab[]).map(x=><Button key={x} variant={tab===x?"primary":"secondary"} onClick={()=>setTab(x)}>{x[0].toUpperCase()+x.slice(1)}</Button>)}</div>
  {err&&<div className="rounded bg-red-50 p-3 text-red-700">{err}</div>}
  {tab==="employees"&&<div className="grid gap-4 xl:grid-cols-[1fr_360px]"><section className="rounded-lg border bg-white"><div className="divide-y">{d?.employees.map(e=><div key={e.uuid} className="flex items-center justify-between p-4"><div><b>{e.name}</b><div className="text-sm text-app-subtle">{e.employeeCode} · {e.designation||e.systemRole} · {e.department||"General"}</div></div><div className="text-right"><b>{formatCurrency(e.baseSalaryMinor)}</b><div className="text-xs">{e.isActive?"Active":"Inactive"}</div></div></div>)}</div></section><section className="h-fit rounded-lg border bg-white p-4"><h2 className="font-extrabold">New Employee</h2><Field l="Name" v={f.name} set={v=>setF({...f,name:v})}/><Field l="Username" v={f.username} set={v=>setF({...f,username:v})}/><Field l="Employee Code" v={f.employeeCode} set={v=>setF({...f,employeeCode:v})}/><Field l="Password" v={f.password||""} set={v=>setF({...f,password:v})}/><Field l="PIN" v={f.pin||""} set={v=>setF({...f,pin:v})}/><Field l="Department" v={f.department||""} set={v=>setF({...f,department:v})}/><Field l="Designation" v={f.designation||""} set={v=>setF({...f,designation:v})}/><label className="mt-3 block text-sm font-semibold">Role<select className="mt-1 h-11 w-full rounded border px-2" value={f.systemRole} onChange={e=>setF({...f,systemRole:e.target.value as SaveEmployeeInput["systemRole"]})}>{["admin","manager","cashier","waiter","kitchen"].map(x=><option key={x}>{x}</option>)}</select></label><Num l="Base salary (minor)" v={f.baseSalaryMinor} set={v=>setF({...f,baseSalaryMinor:v})}/><Button className="mt-3" disabled={!f.name||!f.username||!f.employeeCode} onClick={()=>void save()}>Save Employee</Button></section></div>}
  {tab==="attendance"&&<section className="rounded-lg border bg-white"><div className="divide-y">{d?.employees.map(e=>{const open=d.attendance.find(a=>a.employeeUuid===e.uuid&&!a.checkOutAt);return <div key={e.uuid} className="flex items-center justify-between p-4"><div><b>{e.name}</b><div className="text-sm text-app-subtle">{open?`In since ${new Date(open.checkInAt).toLocaleTimeString()}`:"Not checked in"}</div></div><Button variant={open?"danger":"primary"} onClick={async()=>{const r=open?await requirePosApi().staff.checkOut({employeeUuid:e.uuid}):await requirePosApi().staff.checkIn({employeeUuid:e.uuid});if(r.success)await load();else setErr(r.error.message)}}>{open?"Check Out":"Check In"}</Button></div>})}</div></section>}
  {tab==="roles"&&<section className="rounded-lg border bg-white p-4"><div className="grid gap-3 md:grid-cols-2">{d?.roles.map(r=><div key={r.uuid} className="rounded border p-3"><b>{r.name}</b><div className="mt-2 text-sm text-app-subtle">{r.permissions.join(" · ")||"No permissions"}</div></div>)}</div></section>}
  {tab==="payroll"&&<section className="rounded-lg border bg-white"><div className="divide-y">{d?.employees.map(e=><div key={e.uuid} className="flex items-center justify-between p-4"><div><b>{e.name}</b><div className="text-sm text-app-subtle">Base {formatCurrency(e.baseSalaryMinor)}</div></div><Button variant="secondary" onClick={async()=>{const period=new Date().toISOString().slice(0,7);const r=await requirePosApi().staff.savePayroll({employeeUuid:e.uuid,period});if(r.success)await load();else setErr(r.error.message)}}>Generate {new Date().toISOString().slice(0,7)}</Button></div>)}</div></section>}
  {tab==="audit"&&<section className="rounded-lg border bg-white"><div className="divide-y">{d?.auditLogs.map(a=><div key={a.uuid} className="p-3 text-sm"><b>{a.action}</b> · {a.entityType}<div className="text-xs text-app-subtle">{a.userName||"System"} · {new Date(a.createdAt).toLocaleString()}</div></div>)}</div></section>}
 </div>
}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded bg-app-muted px-3 py-2"><div className="text-[10px] font-bold uppercase text-app-subtle">{label}</div><b>{value}</b></div>}
function Field({l,v,set}:{l:string;v:string;set:(v:string)=>void}){return <label className="mt-3 block text-sm font-semibold">{l}<input className="mt-1 h-11 w-full rounded border px-3 font-normal" value={v} onChange={e=>set(e.target.value)}/></label>}
function Num({l,v,set}:{l:string;v:number;set:(v:number)=>void}){return <label className="mt-3 block text-sm font-semibold">{l}<input type="number" className="mt-1 h-11 w-full rounded border px-3 font-normal" value={v} onChange={e=>set(Number(e.target.value))}/></label>}
