<?php
use Illuminate\Database\Migrations\Migration; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\Schema;
return new class extends Migration { public function up(): void {
Schema::create('tenants', function(Blueprint $t){$t->id();$t->uuid('uuid')->unique();$t->string('name');$t->string('status',20)->default('active')->index();$t->timestamps();});
Schema::create('restaurants', function(Blueprint $t){$t->id();$t->foreignId('tenant_id')->constrained()->cascadeOnDelete();$t->uuid('uuid')->unique();$t->string('code',50)->unique();$t->string('name');$t->string('owner_email',191)->index();$t->string('owner_mobile',20)->index();$t->string('timezone',64)->default('Asia/Kolkata');$t->char('currency',3)->default('INR');$t->string('locale',10)->default('en-IN');$t->string('status',20)->default('active')->index();$t->timestamps();});
Schema::create('license_plans', function(Blueprint $t){$t->id();$t->uuid('uuid')->unique();$t->string('name');$t->json('features');$t->unsignedInteger('outlet_limit')->default(1);$t->unsignedInteger('terminal_limit')->default(1);$t->timestamps();});
Schema::create('licenses', function(Blueprint $t){$t->id();$t->uuid('uuid')->unique();$t->foreignId('tenant_id')->constrained()->cascadeOnDelete();$t->foreignId('restaurant_id')->constrained()->cascadeOnDelete();$t->foreignId('license_plan_id')->constrained();$t->string('key_hash',64)->unique();$t->string('key_last4',4);$t->string('status',20)->index();$t->timestamp('starts_at');$t->timestamp('expires_at')->nullable();$t->timestamp('suspended_at')->nullable();$t->timestamp('revoked_at')->nullable();$t->timestamps();});
Schema::create('subscriptions', function(Blueprint $t){$t->id();$t->uuid('uuid')->unique();$t->foreignId('tenant_id')->constrained()->cascadeOnDelete();$t->foreignId('restaurant_id')->constrained()->cascadeOnDelete();$t->string('plan_code',30);$t->string('billing_cycle',20);$t->string('status',20)->index();$t->timestamp('starts_at');$t->timestamp('ends_at');$t->timestamp('grace_ends_at')->nullable();$t->timestamps();});
Schema::create('devices', function(Blueprint $t){$t->id();$t->uuid('uuid')->unique();$t->foreignId('tenant_id')->constrained()->cascadeOnDelete();$t->foreignId('restaurant_id')->constrained()->cascadeOnDelete();$t->foreignId('license_id')->constrained()->cascadeOnDelete();$t->uuid('client_device_uuid');$t->string('machine_fingerprint',64);$t->string('windows_username',120)->nullable();$t->string('computer_name',120)->nullable();$t->string('app_version',30);$t->string('status',20)->default('active')->index();$t->timestamp('activated_at');$t->timestamp('last_seen_at')->nullable();$t->timestamps();$t->unique(['restaurant_id','client_device_uuid']);$t->unique(['restaurant_id','machine_fingerprint']);});
Schema::create('activation_attempts', function(Blueprint $t){$t->id();$t->uuid('uuid')->unique();$t->string('restaurant_code',50)->nullable()->index();$t->string('owner_email',191)->nullable();$t->string('ip_address',45)->nullable();$t->string('machine_fingerprint',64)->nullable();$t->boolean('successful')->default(false)->index();$t->string('failure_code',60)->nullable();$t->json('metadata')->nullable();$t->timestamps();});
Schema::create('audit_logs', function(Blueprint $t){$t->id();$t->uuid('uuid')->unique();$t->foreignId('tenant_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('restaurant_id')->nullable()->constrained()->nullOnDelete();$t->string('event',80)->index();$t->string('actor_type',60)->nullable();$t->uuid('actor_uuid')->nullable();$t->json('context')->nullable();$t->string('ip_address',45)->nullable();$t->timestamps();});
} public function down(): void { foreach(['audit_logs','activation_attempts','devices','subscriptions','licenses','license_plans','restaurants','tenants'] as $x) Schema::dropIfExists($x); }};
