import { useEffect, useState } from "react";
import type { SalesReport } from "../../../shared/contracts/report-contracts";
import { Button } from "../../components/ui/Button";
import { requirePosApi } from "../../utils/pos-api";
import { formatCurrency } from "../../utils/money";
function dateInput(daysAgo:number){const d=new Date();d.setDate(d.getDate()-daysAgo);return d.toISOString().slice(0,10);}
export function ReportsScreen(){const[from,setFrom]=useState(dateInput(7));const[to,setTo]=useState(dateInput(0));const[data,setData]=useState<SalesReport|null>(null);const[error,setError]=useState<string|null>(null);
 const load=async()=>{const r=await requirePosApi().reports.sales({from:new Date(`${from}T00:00:00`).toISOString(),to:new Date(`${to}T23:59:59.999`).toISOString()});if(r.success){setData(r.data);setError(null);}else setError(r.error.message);};useEffect(()=>{void load();},[]);
 return <div className="space-y-4"><section className="flex flex-wrap items-end gap-3 rounded-lg border border-app-border bg-white p-4"><DateField label="From" value={from} set={setFrom}/><DateField label="To" value={to} set={setTo}/><Button onClick={()=>void load()}>Generate</Button></section>{error&&<div className="rounded-md bg-red-50 p-3 text-red-700">{error}</div>}{data&&<>
  <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Card label="Net Sales" value={formatCurrency(data.summary.netSalesMinor)}/><Card label="Orders" value={String(data.summary.orderCount)}/><Card label="Average Order" value={formatCurrency(data.summary.averageOrderMinor)}/><Card label="GST" value={formatCurrency(data.summary.taxMinor)}/><Card label="Discount" value={formatCurrency(data.summary.discountMinor)}/></div>
  <div className="grid gap-4 xl:grid-cols-2"><section className="rounded-lg border border-app-border bg-white"><h2 className="border-b border-app-border p-4 text-lg font-extrabold">Daily Sales</h2><div className="divide-y divide-app-border">{data.daily.map(r=><div key={r.date} className="grid grid-cols-3 p-3 text-sm"><span>{r.date}</span><span>{r.orderCount} orders</span><strong className="text-right">{formatCurrency(r.netSalesMinor)}</strong></div>)}{!data.daily.length&&<div className="p-6 text-center text-app-subtle">No settled sales.</div>}</div></section>
  <section className="rounded-lg border border-app-border bg-white"><h2 className="border-b border-app-border p-4 text-lg font-extrabold">Top Items</h2><div className="divide-y divide-app-border">{data.topItems.map(r=><div key={r.productName} className="grid grid-cols-[1fr_70px_110px] p-3 text-sm"><span>{r.productName}</span><span>{r.quantity}</span><strong className="text-right">{formatCurrency(r.salesMinor)}</strong></div>)}{!data.topItems.length&&<div className="p-6 text-center text-app-subtle">No item sales.</div>}</div></section></div>
  <section className="rounded-lg border border-app-border bg-white p-4"><h2 className="font-extrabold">Payment Summary</h2><div className="mt-3 grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Card label="Cash" value={formatCurrency(data.summary.cashMinor)}/><Card label="UPI" value={formatCurrency(data.summary.upiMinor)}/><Card label="Card" value={formatCurrency(data.summary.cardMinor)}/><Card label="Credit" value={formatCurrency(data.summary.creditMinor)}/><Card label="Custom" value={formatCurrency(data.summary.customMinor)}/></div></section>
 </>}</div>}
function DateField({label,value,set}:{label:string;value:string;set:(v:string)=>void}){return <label className="text-sm font-semibold">{label}<input type="date" value={value} onChange={e=>set(e.target.value)} className="mt-1 block h-11 rounded-md border border-app-border px-3 font-normal"/></label>};function Card({label,value}:{label:string;value:string}){return <div className="rounded-lg border border-app-border bg-white p-4"><div className="text-xs font-bold uppercase text-app-subtle">{label}</div><div className="mt-1 text-xl font-extrabold">{value}</div></div>}
