import { randomUUID } from "node:crypto";
import type Database from "better-sqlite3";
import type { CreateFinanceEntryInput, FinanceAccount, FinanceDashboard, FinanceEntry, SaveFinanceAccountInput } from "../../shared/contracts/accounting-contracts";
type AccountRow={uuid:string;name:string;account_type:FinanceAccount["accountType"];opening_balance_minor:number;is_active:number;created_at:string;updated_at:string};
type EntryRow={uuid:string;entry_date:string;entry_type:FinanceEntry["entryType"];account_uuid:string;account_name:string;counter_account_uuid:string|null;amount_minor:number;description:string;payment_mode:string;created_at:string};
export class AccountingService{constructor(private readonly db:Database.Database){}
 dashboard():FinanceDashboard{this.ensureDefaults();const accounts=this.listAccounts();const recentEntries=(this.db.prepare(`SELECT e.uuid,e.entry_date,e.entry_type,e.account_uuid,a.name account_name,e.counter_account_uuid,e.amount_minor,e.description,e.payment_mode,e.created_at FROM finance_entries e JOIN finance_accounts a ON a.uuid=e.account_uuid ORDER BY e.entry_date DESC,e.id DESC LIMIT 100`).all() as EntryRow[]).map(mapEntry);const sums=this.db.prepare(`SELECT COALESCE(SUM(CASE WHEN entry_type='income' THEN amount_minor ELSE 0 END),0) income,COALESCE(SUM(CASE WHEN entry_type='expense' THEN amount_minor ELSE 0 END),0) expense,COALESCE(SUM(CASE WHEN entry_type='supplier_payment' THEN amount_minor ELSE 0 END),0) supplier,COALESCE(SUM(CASE WHEN entry_type='customer_receipt' THEN amount_minor ELSE 0 END),0) customer FROM finance_entries`).get() as {income:number;expense:number;supplier:number;customer:number};const opening=accounts.filter(a=>a.accountType==='cash').reduce((n,a)=>n+a.openingBalanceMinor,0);return{accounts,recentEntries,summary:{incomeMinor:sums.income,expenseMinor:sums.expense,supplierPaymentsMinor:sums.supplier,customerReceiptsMinor:sums.customer,netProfitMinor:sums.income-sums.expense,cashBookMinor:opening+sums.income+sums.customer-sums.expense-sums.supplier}};}
 saveAccount(input:SaveFinanceAccountInput):FinanceAccount{const now=new Date().toISOString();const uuid=input.uuid??randomUUID();this.db.prepare(`INSERT INTO finance_accounts(uuid,name,account_type,opening_balance_minor,is_active,created_at,updated_at) VALUES(?,?,?,?,?,?,?) ON CONFLICT(uuid) DO UPDATE SET name=excluded.name,account_type=excluded.account_type,opening_balance_minor=excluded.opening_balance_minor,is_active=excluded.is_active,updated_at=excluded.updated_at`).run(uuid,input.name,input.accountType,input.openingBalanceMinor??0,input.isActive===false?0:1,now,now);return this.listAccounts().find(a=>a.uuid===uuid)!;}
 createEntry(input:CreateFinanceEntryInput,userUuid:string):FinanceEntry{const account=this.db.prepare(`SELECT uuid FROM finance_accounts WHERE uuid=? AND is_active=1`).get(input.accountUuid);if(!account)throw new Error("FINANCE_ACCOUNT_NOT_FOUND");const uuid=randomUUID(),now=new Date().toISOString();this.db.prepare(`INSERT INTO finance_entries(uuid,entry_date,entry_type,account_uuid,counter_account_uuid,amount_minor,reference_type,reference_uuid,description,payment_mode,created_by_user_uuid,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)`).run(uuid,input.entryDate,input.entryType,input.accountUuid,input.counterAccountUuid??null,input.amountMinor,input.referenceType??null,input.referenceUuid??null,input.description,input.paymentMode??"cash",userUuid,now);return this.getEntry(uuid)!;}
 private listAccounts():FinanceAccount[]{return (this.db.prepare(`SELECT * FROM finance_accounts ORDER BY account_type,name`).all() as AccountRow[]).map(r=>({uuid:r.uuid,name:r.name,accountType:r.account_type,openingBalanceMinor:r.opening_balance_minor,isActive:Boolean(r.is_active),createdAt:r.created_at,updatedAt:r.updated_at}));}
 private getEntry(uuid:string):FinanceEntry|null{const r=this.db.prepare(`SELECT e.uuid,e.entry_date,e.entry_type,e.account_uuid,a.name account_name,e.counter_account_uuid,e.amount_minor,e.description,e.payment_mode,e.created_at FROM finance_entries e JOIN finance_accounts a ON a.uuid=e.account_uuid WHERE e.uuid=?`).get(uuid) as EntryRow|undefined;return r?mapEntry(r):null;}
 private ensureDefaults(){const row=this.db.prepare(`SELECT COUNT(*) count FROM finance_accounts`).get() as {count:number};if(row.count)return;const now=new Date().toISOString();const ins=this.db.prepare(`INSERT INTO finance_accounts(uuid,name,account_type,opening_balance_minor,is_active,created_at,updated_at) VALUES(?,?,?,?,1,?,?)`);for(const [name,type] of [["Cash Drawer","cash"],["General Expense","expense"],["Sales Income","income"],["Bank Account","bank"]] as const)ins.run(randomUUID(),name,type,0,now,now);}}
function mapEntry(r:EntryRow):FinanceEntry{return{uuid:r.uuid,entryDate:r.entry_date,entryType:r.entry_type,accountUuid:r.account_uuid,accountName:r.account_name,counterAccountUuid:r.counter_account_uuid,amountMinor:r.amount_minor,description:r.description,paymentMode:r.payment_mode,createdAt:r.created_at};}
