import type Database from "better-sqlite3";
import type { PrinterDiagnostics, SavePrinterInput, SavePrinterRouteInput } from "../../shared/contracts/printer-contracts";
import { PrinterRepository } from "../repositories/printer-repository";
import { BillingRepository } from "../repositories/billing-repository";
import { KotRepository } from "../repositories/kot-repository";
import { center,columns,escposDocument } from "../printers/escpos";
import { diagnose,sendToPrinter } from "../printers/transports";
export class PrinterError extends Error{constructor(public readonly code:string,message:string){super(message);}}
export class PrinterService{
 private readonly repo:PrinterRepository;private readonly bills:BillingRepository;private readonly kots:KotRepository;
 constructor(private readonly db:Database.Database){this.repo=new PrinterRepository(db);this.bills=new BillingRepository(db);this.kots=new KotRepository(db);}
 listPrinters(){return this.repo.list();} savePrinter(i:SavePrinterInput){return this.repo.save(i);} listRoutes(){return this.repo.routes();} saveRoute(i:SavePrinterRouteInput){if(!this.repo.get(i.printerUuid))throw new PrinterError("NOT_FOUND","Printer not found.");return this.repo.saveRoute(i);} listJobs(){return this.repo.listJobs();}
 async diagnostics(printerUuid:string):Promise<PrinterDiagnostics>{const p=this.require(printerUuid),r=await diagnose(p);return{printer:p,...r,checkedAt:new Date().toISOString()};}
 queueTest(printerUuid:string,userUuid:string){const p=this.require(printerUuid);return{printJobUuid:this.repo.createJob({documentType:p.role==="receipt"?"receipt":"kot",documentUuid:p.uuid,printerUuid:p.uuid,copyType:"original",jobKind:"test",payload:{title:"MealHi5 POS",subtitle:"Printer test",createdAt:new Date().toISOString()},userUuid})};}
 queueDrawer(printerUuid:string,userUuid:string){const p=this.require(printerUuid);return{printJobUuid:this.repo.createJob({documentType:"receipt",documentUuid:p.uuid,printerUuid:p.uuid,copyType:"original",jobKind:"drawer",payload:{drawer:true},userUuid})};}
 queueKot(kotUuid:string,userUuid:string,printerUuid?:string){const kot=this.kots.getDetail(kotUuid);if(!kot)throw new PrinterError("NOT_FOUND","KOT not found.");const p=printerUuid?this.require(printerUuid):this.repo.getDefault("kitchen");if(!p)throw new PrinterError("NO_PRINTER","Configure an active kitchen printer first.");const count=(this.db.prepare("SELECT COUNT(*) total FROM print_jobs WHERE document_type='kot' AND document_uuid=?").get(kotUuid) as {total:number}).total;return{printJobUuid:this.repo.createJob({documentType:"kot",documentUuid:kotUuid,printerUuid:p.uuid,copyType:count?"duplicate":"original",jobKind:"print",payload:kot,userUuid})};}
 assignUnroutedReceiptJobs(){const p=this.repo.getDefault("receipt");if(!p)return 0;const rows=this.db.prepare("SELECT uuid FROM print_jobs WHERE document_type='receipt' AND printer_uuid IS NULL AND status='pending'").all() as {uuid:string}[];for(const r of rows)this.repo.assignJob(r.uuid,p.uuid,new Date().toISOString());return rows.length;}
 async processQueue(limit=20){this.assignUnroutedReceiptJobs();const jobs=this.repo.pending(limit);let printed=0,failed=0;for(const job of jobs){try{if(!job.printerUuid)throw new Error("No printer assigned.");const p=this.require(job.printerUuid);const data=this.render(p,job.jobKind,job.documentType,JSON.parse(job.payloadJson));await sendToPrinter(p,data);this.repo.markPrinted(job.uuid);printed++;}catch(e){this.repo.markFailed(job.uuid,e instanceof Error?e.message:"Unknown print error");failed++;}}return{processed:printed+failed,printed,failed};}
 retry(printJobUuid:string){this.repo.retry(printJobUuid);return{retried:true as const};}
 private render(p:any,kind:string,documentType:string,payload:any){const w=p.charactersPerLine;if(kind==="drawer")return escposDocument([],{cut:false,drawer:true});if(kind==="test")return escposDocument([center("MEALHI5 POS",w),center("PRINTER TEST",w),"-".repeat(w),columns("Printer",p.name,w),columns("Connection",p.connectionType,w),new Date().toLocaleString()],{cut:p.autoCut,drawer:false});if(documentType==="receipt")return escposDocument([center("MEALHI5 POS",w),center(payload.copyType==="duplicate"?"DUPLICATE RECEIPT":"RECEIPT",w),"-".repeat(w),columns("Bill",payload.billNo??"",w),columns("Order",payload.orderNo??"",w),"-".repeat(w),columns("Subtotal",money(payload.subtotalMinor),w),columns("Discount",money(payload.discountMinor),w),columns("GST",money(payload.taxMinor),w),columns("TOTAL",money(payload.grandTotalMinor),w),"-".repeat(w),center("Thank you",w)],{cut:p.autoCut,drawer:p.openCashDrawer});const lines=[center(`KOT ${payload.kind?.toUpperCase?.()??""}`,w),columns("Order",payload.orderNo??"",w),columns("Status",payload.status??"",w),"-".repeat(w),...(payload.items??[]).flatMap((i:any)=>[`${String(i.lineAction).toUpperCase()} ${i.qty} x ${i.itemName}${i.variantName?` (${i.variantName})`:""}`,...(i.modifierNames?.length?[`  ${i.modifierNames.join(", ")}`]:[]),...(i.kitchenNote?[`  Note: ${i.kitchenNote}`]:[])]),"-".repeat(w)];return escposDocument(lines,{cut:p.autoCut,drawer:false});}
 private require(uuid:string){const p=this.repo.get(uuid);if(!p)throw new PrinterError("NOT_FOUND","Printer not found.");if(!p.isActive)throw new PrinterError("INACTIVE_PRINTER","Printer is inactive.");return p;}
}
const money=(n:number)=>`Rs ${(Number(n||0)/100).toFixed(2)}`;
