import { useEffect, useState } from "react";
import type { InventoryDashboard, SaveInventoryItemInput } from "../../../shared/contracts/inventory-contracts";
import { Button } from "../../components/ui/Button";
import { requirePosApi } from "../../utils/pos-api";
import { formatCurrency } from "../../utils/money";

type Tab="stock"|"purchases"|"suppliers"|"recipes";
const emptyItem:SaveInventoryItemInput={name:"",sku:"",unit:"kg",reorderLevel:0,costPerUnitMinor:0,openingQty:0,isActive:true};
export function InventoryScreen(){
  const [data,setData]=useState<InventoryDashboard|null>(null); const [tab,setTab]=useState<Tab>("stock"); const [form,setForm]=useState(emptyItem); const [error,setError]=useState<string|null>(null); const [busy,setBusy]=useState(false);
  const load=async()=>{setBusy(true);const r=await requirePosApi().inventory.dashboard();setBusy(false);if(r.success){setData(r.data);setError(null)}else setError(r.error.message)};
  useEffect(()=>{void load()},[]);
  const save=async()=>{const r=await requirePosApi().inventory.saveItem(form);if(r.success){setForm(emptyItem);await load()}else setError(r.error.message)};
  const adjust=async(itemUuid:string,type:"wastage"|"adjustment")=>{const raw=window.prompt(type==="wastage"?"Wastage quantity":"Adjustment quantity (+/-)","1");if(!raw)return;const qtyDelta=Number(raw);if(!Number.isFinite(qtyDelta)||qtyDelta===0)return;const r=await requirePosApi().inventory.adjust({itemUuid,qtyDelta,type,notes:type});if(r.success)await load();else setError(r.error.message)};
  return <div className="space-y-4">
    <section className="flex flex-wrap items-center justify-between gap-3 rounded-lg border border-app-border bg-white p-4"><div><h1 className="text-xl font-extrabold">Inventory & Recipes</h1><p className="text-sm text-app-subtle">Stock, suppliers, purchases, wastage and product recipes.</p></div><div className="flex gap-2"><Metric label="Items" value={String(data?.items.length??0)}/><Metric label="Low Stock" value={String(data?.lowStockCount??0)}/><Metric label="Value" value={formatCurrency(data?.stockValueMinor??0)}/><Button variant="secondary" onClick={()=>void load()}>Refresh</Button></div></section>
    <div className="flex flex-wrap gap-2">{(["stock","purchases","suppliers","recipes"] as Tab[]).map(t=><Button key={t} variant={tab===t?"primary":"secondary"} onClick={()=>setTab(t)}>{t[0].toUpperCase()+t.slice(1)}</Button>)}</div>
    {error&&<div className="rounded-md bg-red-50 p-3 text-sm text-red-700">{error}</div>}
    {tab==="stock"&&<div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_360px]">
      <section className="overflow-hidden rounded-lg border border-app-border bg-white"><div className="grid grid-cols-[1fr_90px_100px_100px_155px] gap-2 border-b border-app-border bg-app-muted p-3 text-xs font-bold uppercase"><span>Item</span><span>Unit</span><span>On Hand</span><span>Reorder</span><span>Actions</span></div><div className="divide-y divide-app-border">{data?.items.map(i=><div key={i.uuid} className={`grid grid-cols-[1fr_90px_100px_100px_155px] items-center gap-2 p-3 text-sm ${i.isLowStock?"bg-amber-50":""}`}><div><div className="font-bold">{i.name}</div><div className="text-xs text-app-subtle">{i.sku||"No SKU"} · {formatCurrency(i.costPerUnitMinor)}/{i.unit}</div></div><span>{i.unit}</span><span className="font-bold">{i.onHand.toFixed(2)}</span><span>{i.reorderLevel}</span><div className="flex gap-1"><Button variant="secondary" className="h-8 px-2" onClick={()=>void adjust(i.uuid,"adjustment")}>Adjust</Button><Button variant="danger" className="h-8 px-2" onClick={()=>void adjust(i.uuid,"wastage")}>Waste</Button></div></div>)}{!busy&&!data?.items.length&&<div className="p-8 text-center text-app-subtle">No inventory items.</div>}</div></section>
      <section className="h-fit rounded-lg border border-app-border bg-white p-4"><h2 className="font-extrabold">New Stock Item</h2><div className="mt-3 space-y-3"><Field label="Name" value={form.name} onChange={v=>setForm({...form,name:v})}/><Field label="SKU" value={form.sku??""} onChange={v=>setForm({...form,sku:v})}/><Field label="Unit" value={form.unit} onChange={v=>setForm({...form,unit:v})}/><Num label="Opening Qty" value={form.openingQty??0} onChange={v=>setForm({...form,openingQty:v})}/><Num label="Reorder Level" value={form.reorderLevel} onChange={v=>setForm({...form,reorderLevel:v})}/><Num label="Cost (minor units)" value={form.costPerUnitMinor} onChange={v=>setForm({...form,costPerUnitMinor:v})}/><Button disabled={form.name.trim().length<2} onClick={()=>void save()}>Save Item</Button></div></section>
    </div>}
    {tab==="suppliers"&&<Suppliers data={data} reload={load} setError={setError}/>} 
    {tab==="purchases"&&<Purchases data={data} reload={load} setError={setError}/>} 
    {tab==="recipes"&&<section className="rounded-lg border border-app-border bg-white"><div className="border-b p-4"><h2 className="font-extrabold">Recipes</h2><p className="text-sm text-app-subtle">Recipe database and service are active. Recipe editor is prepared for the next UI refinement.</p></div><div className="divide-y">{data?.recipes.map(r=><div key={r.uuid} className="p-4"><div className="font-bold">{r.productName} · Yield {r.yieldQty}</div><div className="text-sm text-app-subtle">{r.items.map(x=>`${x.itemName}: ${x.qty} ${x.unit}`).join(" · ")}</div></div>)}{!data?.recipes.length&&<div className="p-8 text-center text-app-subtle">No recipes configured.</div>}</div></section>}
  </div>;
}
function Suppliers({data,reload,setError}:{data:InventoryDashboard|null;reload:()=>Promise<void>;setError:(x:string|null)=>void}){const [name,setName]=useState(""),[phone,setPhone]=useState("");return <div className="grid gap-4 xl:grid-cols-[1fr_360px]"><section className="rounded-lg border bg-white"><div className="divide-y">{data?.suppliers.map(s=><div className="p-4" key={s.uuid}><b>{s.name}</b><div className="text-sm text-app-subtle">{s.phone||"No phone"} · {s.email||"No email"}</div></div>)}</div></section><section className="h-fit rounded-lg border bg-white p-4"><h2 className="font-extrabold">New Supplier</h2><Field label="Name" value={name} onChange={setName}/><Field label="Phone" value={phone} onChange={setPhone}/><Button className="mt-3" onClick={async()=>{const r=await requirePosApi().inventory.saveSupplier({name,phone});if(r.success){setName("");setPhone("");await reload()}else setError(r.error.message)}}>Save Supplier</Button></section></div>}
function Purchases({data,reload,setError}:{data:InventoryDashboard|null;reload:()=>Promise<void>;setError:(x:string|null)=>void}){const [supplierUuid,setSupplier]=useState(""),[itemUuid,setItem]=useState(""),[qty,setQty]=useState(1),[cost,setCost]=useState(0);return <div className="grid gap-4 xl:grid-cols-[1fr_360px]"><section className="rounded-lg border bg-white"><div className="divide-y">{data?.purchases.map(p=><div key={p.uuid} className="flex items-center justify-between p-4"><div><b>{p.purchaseNo}</b><div className="text-sm text-app-subtle">{p.supplierName||"No supplier"} · {new Date(p.purchasedAt).toLocaleString()}</div></div><div className="flex items-center gap-3"><b>{formatCurrency(p.totalMinor)}</b><span className="text-xs uppercase">{p.status}</span>{p.status==="posted"&&<Button variant="danger" onClick={async()=>{const r=await requirePosApi().inventory.cancelPurchase({purchaseUuid:p.uuid});if(r.success)await reload();else setError(r.error.message)}}>Cancel</Button>}</div></div>)}</div></section><section className="h-fit rounded-lg border bg-white p-4"><h2 className="font-extrabold">Quick Purchase</h2><select className="mt-3 h-11 w-full rounded-md border px-2" value={supplierUuid} onChange={e=>setSupplier(e.target.value)}><option value="">No supplier</option>{data?.suppliers.map(s=><option key={s.uuid} value={s.uuid}>{s.name}</option>)}</select><select className="mt-3 h-11 w-full rounded-md border px-2" value={itemUuid} onChange={e=>setItem(e.target.value)}><option value="">Select item</option>{data?.items.map(i=><option key={i.uuid} value={i.uuid}>{i.name}</option>)}</select><Num label="Quantity" value={qty} onChange={setQty}/><Num label="Unit cost (minor)" value={cost} onChange={setCost}/><Button className="mt-3" onClick={async()=>{if(!itemUuid)return;const r=await requirePosApi().inventory.createPurchase({supplierUuid:supplierUuid||undefined,purchasedAt:new Date().toISOString(),items:[{inventoryItemUuid:itemUuid,qty,unitCostMinor:cost}]});if(r.success)await reload();else setError(r.error.message)}}>Post Purchase</Button></section></div>}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-md bg-app-muted px-3 py-2"><div className="text-[10px] font-bold uppercase text-app-subtle">{label}</div><div className="font-extrabold">{value}</div></div>}
function Field({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label className="mt-3 block text-sm font-semibold">{label}<input className="mt-1 h-11 w-full rounded-md border px-3 font-normal" value={value} onChange={e=>onChange(e.target.value)}/></label>}
function Num({label,value,onChange}:{label:string;value:number;onChange:(v:number)=>void}){return <label className="mt-3 block text-sm font-semibold">{label}<input type="number" step="0.01" className="mt-1 h-11 w-full rounded-md border px-3 font-normal" value={value} onChange={e=>onChange(Number(e.target.value))}/></label>}
