import { randomUUID } from "node:crypto";
import type Database from "better-sqlite3";
import type { AdjustLoyaltyInput, Coupon, CrmDashboard, LoyaltyAccount, LoyaltyTransaction, Membership, SaveCouponInput, SaveMembershipInput } from "../../shared/contracts/crm-contracts";

type AccountRow={customer_uuid:string;customer_name:string;phone:string|null;points_balance:number;wallet_minor:number;tier:LoyaltyAccount["tier"]};
type TxRow={uuid:string;customer_uuid:string;transaction_type:LoyaltyTransaction["transactionType"];direction:LoyaltyTransaction["direction"];amount:number;reason:string;created_at:string};
type CouponRow={uuid:string;code:string;name:string;discount_type:Coupon["discountType"];discount_value:number;min_order_minor:number;max_discount_minor:number|null;starts_at:string|null;ends_at:string|null;usage_limit:number|null;used_count:number;is_active:0|1};
type MembershipRow={uuid:string;customer_uuid:string;customer_name:string;plan_name:string;starts_at:string;ends_at:string;status:Membership["status"]};

export class CrmRepository{
 constructor(private readonly db:Database.Database){}
 dashboard():CrmDashboard{return{accounts:this.accounts(),recentTransactions:this.transactions(),coupons:this.coupons(),memberships:this.memberships()};}
 accounts():LoyaltyAccount[]{return (this.db.prepare(`SELECT c.uuid customer_uuid,c.name customer_name,c.phone,COALESCE(l.points_balance,0) points_balance,COALESCE(l.wallet_minor,0) wallet_minor,COALESCE(l.tier,'standard') tier FROM customers c LEFT JOIN loyalty_accounts l ON l.customer_uuid=c.uuid WHERE c.is_active=1 ORDER BY c.name`).all() as AccountRow[]).map(r=>({customerUuid:r.customer_uuid,customerName:r.customer_name,phone:r.phone,pointsBalance:r.points_balance,walletMinor:r.wallet_minor,tier:r.tier}));}
 transactions(limit=50):LoyaltyTransaction[]{return (this.db.prepare(`SELECT uuid,customer_uuid,transaction_type,direction,amount,reason,created_at FROM loyalty_transactions ORDER BY created_at DESC LIMIT ?`).all(limit) as TxRow[]).map(r=>({uuid:r.uuid,customerUuid:r.customer_uuid,transactionType:r.transaction_type,direction:r.direction,amount:r.amount,reason:r.reason,createdAt:r.created_at}));}
 coupons():Coupon[]{return (this.db.prepare(`SELECT uuid,code,name,discount_type,discount_value,min_order_minor,max_discount_minor,starts_at,ends_at,usage_limit,used_count,is_active FROM coupons ORDER BY is_active DESC,code`).all() as CouponRow[]).map(r=>({uuid:r.uuid,code:r.code,name:r.name,discountType:r.discount_type,discountValue:r.discount_value,minOrderMinor:r.min_order_minor,maxDiscountMinor:r.max_discount_minor,startsAt:r.starts_at,endsAt:r.ends_at,usageLimit:r.usage_limit,usedCount:r.used_count,isActive:r.is_active===1}));}
 memberships():Membership[]{return (this.db.prepare(`SELECT m.uuid,m.customer_uuid,c.name customer_name,m.plan_name,m.starts_at,m.ends_at,m.status FROM customer_memberships m JOIN customers c ON c.uuid=m.customer_uuid ORDER BY m.created_at DESC`).all() as MembershipRow[]).map(r=>({uuid:r.uuid,customerUuid:r.customer_uuid,customerName:r.customer_name,planName:r.plan_name,startsAt:r.starts_at,endsAt:r.ends_at,status:r.status}));}
 adjust(input:AdjustLoyaltyInput,userUuid:string|null,now:string):LoyaltyAccount{
  const tx=this.db.transaction(()=>{this.db.prepare(`INSERT INTO loyalty_accounts(customer_uuid,points_balance,wallet_minor,tier,updated_at) VALUES(?,0,0,'standard',?) ON CONFLICT(customer_uuid) DO NOTHING`).run(input.customerUuid,now);const column=input.transactionType==="points"?"points_balance":"wallet_minor";const delta=input.direction==="credit"?input.amount:-input.amount;const current=this.db.prepare(`SELECT ${column} value FROM loyalty_accounts WHERE customer_uuid=?`).get(input.customerUuid) as {value:number}|undefined;if(!current)throw new Error("Loyalty account unavailable.");if(current.value+delta<0)throw Object.assign(new Error("Insufficient balance."),{code:"INSUFFICIENT_BALANCE"});this.db.prepare(`UPDATE loyalty_accounts SET ${column}=${column}+?,updated_at=? WHERE customer_uuid=?`).run(delta,now,input.customerUuid);this.db.prepare(`INSERT INTO loyalty_transactions(uuid,customer_uuid,transaction_type,direction,amount,reason,created_by_user_uuid,created_at) VALUES(?,?,?,?,?,?,?,?)`).run(randomUUID(),input.customerUuid,input.transactionType,input.direction,input.amount,input.reason,userUuid,now);});tx();const result=this.accounts().find(a=>a.customerUuid===input.customerUuid);if(!result)throw new Error("Customer not found.");return result;
 }
 saveCoupon(input:SaveCouponInput,now:string):Coupon{const uuid=input.couponUuid??randomUUID();this.db.prepare(`INSERT INTO coupons(uuid,code,name,discount_type,discount_value,min_order_minor,max_discount_minor,starts_at,ends_at,usage_limit,is_active,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(uuid) DO UPDATE SET code=excluded.code,name=excluded.name,discount_type=excluded.discount_type,discount_value=excluded.discount_value,min_order_minor=excluded.min_order_minor,max_discount_minor=excluded.max_discount_minor,starts_at=excluded.starts_at,ends_at=excluded.ends_at,usage_limit=excluded.usage_limit,is_active=excluded.is_active,updated_at=excluded.updated_at`).run(uuid,input.code,input.name,input.discountType,input.discountValue,input.minOrderMinor??0,input.maxDiscountMinor??null,input.startsAt??null,input.endsAt??null,input.usageLimit??null,input.isActive===false?0:1,now,now);const result=this.coupons().find(c=>c.uuid===uuid);if(!result)throw new Error("Coupon save failed.");return result;}
 saveMembership(input:SaveMembershipInput,now:string):Membership{const uuid=input.membershipUuid??randomUUID();this.db.prepare(`INSERT INTO customer_memberships(uuid,customer_uuid,plan_name,starts_at,ends_at,status,benefits_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?, ?,?) ON CONFLICT(uuid) DO UPDATE SET customer_uuid=excluded.customer_uuid,plan_name=excluded.plan_name,starts_at=excluded.starts_at,ends_at=excluded.ends_at,status=excluded.status,updated_at=excluded.updated_at`).run(uuid,input.customerUuid,input.planName,input.startsAt,input.endsAt,input.status??"active","{}",now,now);const result=this.memberships().find(m=>m.uuid===uuid);if(!result)throw new Error("Membership save failed.");return result;}
}
