import { randomUUID } from "node:crypto";
import type Database from "better-sqlite3";
import type { AssignModifierGroupInput, MenuCategoryAdmin, MenuDashboard, MenuProductAdmin, SaveMenuCategoryInput, SaveMenuProductInput, SaveModifierGroupInput, SaveModifierInput, SaveProductVariantInput } from "../../shared/contracts/menu-management-contracts";
import { ModifierGroupRepository } from "./modifier-group-repository";
import { ProductVariantRepository } from "./product-variant-repository";

type CategoryRow={uuid:string;name:string;code:string;sort_order:number;is_active:0|1;product_count:number};
type ProductRow={uuid:string;category_uuid:string;category_name:string;name:string;description:string|null;sku:string|null;barcode:string|null;base_price_minor:number;gst_mode:"inclusive"|"exclusive";gst_rate_basis_points:number;kitchen_station:string;is_online_visible:0|1;is_favorite:0|1;image_url:string|null;is_active:0|1;sort_order:number};
export class MenuManagementRepository{
 constructor(private readonly db:Database.Database){}
 dashboard():MenuDashboard{
  const categories=(this.db.prepare(`SELECT c.uuid,c.name,c.code,c.sort_order,c.is_active,COUNT(p.uuid) product_count FROM categories c LEFT JOIN products p ON p.category_uuid=c.uuid GROUP BY c.uuid ORDER BY c.sort_order,c.name`).all() as CategoryRow[]).map(r=>({uuid:r.uuid,name:r.name,code:r.code,sortOrder:r.sort_order,isActive:r.is_active===1,productCount:r.product_count}));
  const rows=this.db.prepare(`SELECT p.uuid,p.category_uuid,c.name category_name,p.name,p.description,p.sku,p.barcode,p.base_price_minor,p.gst_mode,p.gst_rate_basis_points,p.kitchen_station,p.is_online_visible,p.is_favorite,p.image_url,p.is_active,p.sort_order FROM products p JOIN categories c ON c.uuid=p.category_uuid ORDER BY c.sort_order,p.sort_order,p.name`).all() as ProductRow[];
  const variants=new ProductVariantRepository(this.db);const modifiers=new ModifierGroupRepository(this.db);
  const products:MenuProductAdmin[]=rows.map(r=>({uuid:r.uuid,categoryUuid:r.category_uuid,categoryName:r.category_name,name:r.name,description:r.description,sku:r.sku,barcode:r.barcode,basePriceMinor:r.base_price_minor,gstMode:r.gst_mode,gstRateBasisPoints:r.gst_rate_basis_points,kitchenStation:r.kitchen_station,isOnlineVisible:r.is_online_visible===1,isFavorite:r.is_favorite===1,imageUrl:r.image_url,isActive:r.is_active===1,sortOrder:r.sort_order,variants:variants.listByProduct(r.uuid),modifierGroups:modifiers.listByProduct(r.uuid)}));
  const modifierGroups=this.listAllModifierGroups();
  const kitchenStations=[...new Set(["main_kitchen","bar","tandoor","dessert",...products.map(p=>p.kitchenStation)])];
  return {categories,products,modifierGroups,kitchenStations};
 }
 saveCategory(i:SaveMenuCategoryInput,now:string):MenuCategoryAdmin{const uuid=i.categoryUuid??randomUUID();this.db.prepare(`INSERT INTO categories(uuid,name,code,sort_order,is_active,created_at,updated_at) VALUES(?,?,?,?,?,?,?) ON CONFLICT(uuid) DO UPDATE SET name=excluded.name,code=excluded.code,sort_order=excluded.sort_order,is_active=excluded.is_active,updated_at=excluded.updated_at`).run(uuid,i.name,i.code.toUpperCase(),i.sortOrder,i.isActive===false?0:1,now,now);return this.dashboard().categories.find(x=>x.uuid===uuid)!;}
 saveProduct(i:SaveMenuProductInput,now:string):MenuProductAdmin{const uuid=i.productUuid??randomUUID();const search=[i.name,i.sku??"",i.barcode??""].join(" ").toLowerCase();this.db.prepare(`INSERT INTO products(uuid,category_uuid,name,description,sku,barcode,base_price_minor,gst_mode,gst_rate_basis_points,is_active,sort_order,search_text,created_at,updated_at,kitchen_station,is_online_visible,is_favorite,image_url) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(uuid) DO UPDATE SET category_uuid=excluded.category_uuid,name=excluded.name,description=excluded.description,sku=excluded.sku,barcode=excluded.barcode,base_price_minor=excluded.base_price_minor,gst_mode=excluded.gst_mode,gst_rate_basis_points=excluded.gst_rate_basis_points,is_active=excluded.is_active,sort_order=excluded.sort_order,search_text=excluded.search_text,updated_at=excluded.updated_at,kitchen_station=excluded.kitchen_station,is_online_visible=excluded.is_online_visible,is_favorite=excluded.is_favorite,image_url=excluded.image_url`).run(uuid,i.categoryUuid,i.name,i.description||null,i.sku||null,i.barcode||null,i.basePriceMinor,i.gstMode,i.gstRateBasisPoints,i.isActive===false?0:1,i.sortOrder,search,now,now,i.kitchenStation,i.isOnlineVisible===false?0:1,i.isFavorite?1:0,i.imageUrl||null);return this.dashboard().products.find(x=>x.uuid===uuid)!;}
 saveVariant(i:SaveProductVariantInput,now:string){const uuid=i.variantUuid??randomUUID();if(i.isDefault)this.db.prepare("UPDATE product_variants SET is_default=0 WHERE product_uuid=?").run(i.productUuid);this.db.prepare(`INSERT INTO product_variants(uuid,product_uuid,name,sku,barcode,price_minor,is_default,is_active,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?) ON CONFLICT(uuid) DO UPDATE SET name=excluded.name,sku=excluded.sku,barcode=excluded.barcode,price_minor=excluded.price_minor,is_default=excluded.is_default,is_active=excluded.is_active,updated_at=excluded.updated_at`).run(uuid,i.productUuid,i.name,i.sku||null,i.barcode||null,i.priceMinor,i.isDefault?1:0,i.isActive===false?0:1,now,now);return new ProductVariantRepository(this.db).listByProduct(i.productUuid).find(x=>x.uuid===uuid)!;}
 saveModifierGroup(i:SaveModifierGroupInput,now:string){const uuid=i.groupUuid??randomUUID();this.db.prepare(`INSERT INTO modifier_groups(uuid,name,code,min_select,max_select,is_required,is_active,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?) ON CONFLICT(uuid) DO UPDATE SET name=excluded.name,code=excluded.code,min_select=excluded.min_select,max_select=excluded.max_select,is_required=excluded.is_required,is_active=excluded.is_active,updated_at=excluded.updated_at`).run(uuid,i.name,i.code.toUpperCase(),i.minSelect,i.maxSelect,i.isRequired?1:0,i.isActive===false?0:1,now,now);return this.listAllModifierGroups().find(x=>x.uuid===uuid)!;}
 saveModifier(i:SaveModifierInput,now:string){const uuid=i.modifierUuid??randomUUID();this.db.prepare(`INSERT INTO modifiers(uuid,modifier_group_uuid,name,code,price_delta_minor,is_active,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(uuid) DO UPDATE SET modifier_group_uuid=excluded.modifier_group_uuid,name=excluded.name,code=excluded.code,price_delta_minor=excluded.price_delta_minor,is_active=excluded.is_active,updated_at=excluded.updated_at`).run(uuid,i.groupUuid,i.name,i.code.toUpperCase(),i.priceDeltaMinor,i.isActive===false?0:1,now,now);return this.listAllModifierGroups().find(g=>g.uuid===i.groupUuid)!;}
 assignModifierGroup(i:AssignModifierGroupInput,now:string){if(i.assigned)this.db.prepare(`INSERT OR IGNORE INTO product_modifier_groups(product_uuid,modifier_group_uuid,sort_order,created_at) VALUES(?,?,0,?)`).run(i.productUuid,i.groupUuid,now);else this.db.prepare("DELETE FROM product_modifier_groups WHERE product_uuid=? AND modifier_group_uuid=?").run(i.productUuid,i.groupUuid);return true;}
 private listAllModifierGroups(){return this.manualGroups();}
 private manualGroups(){const groups=this.db.prepare(`SELECT uuid,name,code,min_select,max_select,is_required FROM modifier_groups ORDER BY name`).all() as Array<{uuid:string;name:string;code:string;min_select:number;max_select:number;is_required:0|1}>;return groups.map(g=>({uuid:g.uuid,name:g.name,code:g.code,minSelect:g.min_select,maxSelect:g.max_select,isRequired:g.is_required===1,modifiers:(this.db.prepare(`SELECT uuid,modifier_group_uuid,name,code,price_delta_minor,is_active FROM modifiers WHERE modifier_group_uuid=? ORDER BY name`).all(g.uuid) as Array<{uuid:string;modifier_group_uuid:string;name:string;code:string;price_delta_minor:number;is_active:0|1}>).map(m=>({uuid:m.uuid,groupUuid:m.modifier_group_uuid,name:m.name,code:m.code,priceDeltaMinor:m.price_delta_minor,isActive:m.is_active===1}))}));}
}
