import { randomUUID } from "node:crypto";
import type Database from "better-sqlite3";
import type { CreateStockTransferInput, MultiOutletDashboard, OutletAdmin, OutletBalance, SaveOutletInput, StockTransferSummary } from "../../shared/contracts/multi-outlet-contracts";

type OutletRow={uuid:string;restaurant_uuid:string;name:string;code:string;address:string|null;city:string|null;state:string|null;postal_code:string|null;phone:string|null;status:"active"|"inactive"};
export class MultiOutletRepository{
 constructor(private readonly db:Database.Database){}
 dashboard(restaurantUuid:string):MultiOutletDashboard{return {outlets:this.listOutlets(restaurantUuid),balances:this.listBalances(restaurantUuid),transfers:this.listTransfers(restaurantUuid)};}
 saveOutlet(restaurantUuid:string,i:SaveOutletInput,now:string):OutletAdmin{const uuid=i.outletUuid??randomUUID();this.db.prepare(`INSERT INTO outlets(uuid,restaurant_uuid,name,code,address,city,state,postal_code,phone,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(uuid) DO UPDATE SET name=excluded.name,code=excluded.code,address=excluded.address,city=excluded.city,state=excluded.state,postal_code=excluded.postal_code,phone=excluded.phone,status=excluded.status,updated_at=excluded.updated_at`).run(uuid,restaurantUuid,i.name,i.code.toUpperCase(),i.address||null,i.city||null,i.state||null,i.postalCode||null,i.phone||null,i.status??"active",now,now);return this.listOutlets(restaurantUuid).find(x=>x.uuid===uuid)!;}
 createTransfer(restaurantUuid:string,i:CreateStockTransferInput,userUuid:string,now:string){const outletCount=(this.db.prepare(`SELECT COUNT(*) count FROM outlets WHERE restaurant_uuid=? AND uuid IN (?,?)`).get(restaurantUuid,i.fromOutletUuid,i.toOutletUuid) as {count:number}).count;if(outletCount!==2)throw new Error("Invalid outlet selection.");const uuid=randomUUID();const transferNo=`TRF-${Date.now()}`;const tx=this.db.transaction(()=>{this.ensureBalances(i.fromOutletUuid,i.items.map(x=>x.inventoryItemUuid),now);for(const line of i.items){const row=this.db.prepare("SELECT on_hand FROM outlet_inventory_balances WHERE outlet_uuid=? AND inventory_item_uuid=?").get(i.fromOutletUuid,line.inventoryItemUuid) as {on_hand:number}|undefined;if((row?.on_hand??0)<line.qty)throw new Error("Insufficient source outlet stock.");}this.db.prepare(`INSERT INTO stock_transfers(uuid,transfer_no,from_outlet_uuid,to_outlet_uuid,status,notes,created_by_user_uuid,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)`).run(uuid,transferNo,i.fromOutletUuid,i.toOutletUuid,"draft",i.notes||null,userUuid,now,now);const stmt=this.db.prepare(`INSERT INTO stock_transfer_items(uuid,transfer_uuid,inventory_item_uuid,qty,created_at) VALUES(?,?,?,?,?)`);for(const line of i.items)stmt.run(randomUUID(),uuid,line.inventoryItemUuid,line.qty,now);});tx();return uuid;}
 sendTransfer(restaurantUuid:string,uuid:string,now:string){const t=this.getTransfer(uuid,restaurantUuid);if(!t||t.status!=="draft")throw new Error("Only draft transfers can be sent.");const tx=this.db.transaction(()=>{const lines=this.lines(uuid);this.ensureBalances(t.fromOutletUuid,lines.map(x=>x.inventoryItemUuid),now);for(const l of lines){const r=this.db.prepare("SELECT on_hand FROM outlet_inventory_balances WHERE outlet_uuid=? AND inventory_item_uuid=?").get(t.fromOutletUuid,l.inventoryItemUuid) as {on_hand:number};if(r.on_hand<l.qty)throw new Error("Insufficient source outlet stock.");this.db.prepare("UPDATE outlet_inventory_balances SET on_hand=on_hand-?,updated_at=? WHERE outlet_uuid=? AND inventory_item_uuid=?").run(l.qty,now,t.fromOutletUuid,l.inventoryItemUuid);}this.db.prepare("UPDATE stock_transfers SET status='sent',sent_at=?,updated_at=? WHERE uuid=?").run(now,now,uuid);});tx();return true;}
 receiveTransfer(restaurantUuid:string,uuid:string,now:string){const t=this.getTransfer(uuid,restaurantUuid);if(!t||t.status!=="sent")throw new Error("Only sent transfers can be received.");const tx=this.db.transaction(()=>{const lines=this.lines(uuid);this.ensureBalances(t.toOutletUuid,lines.map(x=>x.inventoryItemUuid),now);for(const l of lines)this.db.prepare("UPDATE outlet_inventory_balances SET on_hand=on_hand+?,updated_at=? WHERE outlet_uuid=? AND inventory_item_uuid=?").run(l.qty,now,t.toOutletUuid,l.inventoryItemUuid);this.db.prepare("UPDATE stock_transfers SET status='received',received_at=?,updated_at=? WHERE uuid=?").run(now,now,uuid);});tx();return true;}
 seedCurrentOutletBalance(outletUuid:string,now:string){const rows=this.db.prepare(`SELECT i.uuid,COALESCE(SUM(sm.qty_delta),0) qty FROM inventory_items i LEFT JOIN stock_movements sm ON sm.inventory_item_uuid=i.uuid GROUP BY i.uuid`).all() as Array<{uuid:string;qty:number}>;const stmt=this.db.prepare(`INSERT INTO outlet_inventory_balances(outlet_uuid,inventory_item_uuid,on_hand,updated_at) VALUES(?,?,?,?) ON CONFLICT(outlet_uuid,inventory_item_uuid) DO UPDATE SET on_hand=excluded.on_hand,updated_at=excluded.updated_at`);const tx=this.db.transaction(()=>rows.forEach(r=>stmt.run(outletUuid,r.uuid,r.qty,now)));tx();return rows.length;}
 private listOutlets(restaurantUuid:string):OutletAdmin[]{return (this.db.prepare(`SELECT uuid,restaurant_uuid,name,code,address,city,state,postal_code,phone,status FROM outlets WHERE restaurant_uuid=? ORDER BY name`).all(restaurantUuid) as OutletRow[]).map(r=>({uuid:r.uuid,restaurantUuid:r.restaurant_uuid,name:r.name,code:r.code,address:r.address,city:r.city,state:r.state,postalCode:r.postal_code,phone:r.phone,status:r.status}));}
 private listBalances(restaurantUuid:string):OutletBalance[]{return (this.db.prepare(`SELECT b.outlet_uuid,o.name outlet_name,b.inventory_item_uuid,i.name item_name,i.unit,b.on_hand FROM outlet_inventory_balances b JOIN outlets o ON o.uuid=b.outlet_uuid JOIN inventory_items i ON i.uuid=b.inventory_item_uuid WHERE o.restaurant_uuid=? ORDER BY o.name,i.name`).all(restaurantUuid) as Array<{outlet_uuid:string;outlet_name:string;inventory_item_uuid:string;item_name:string;unit:string;on_hand:number}>).map(r=>({outletUuid:r.outlet_uuid,outletName:r.outlet_name,inventoryItemUuid:r.inventory_item_uuid,itemName:r.item_name,unit:r.unit,onHand:r.on_hand}));}
 private listTransfers(restaurantUuid:string):StockTransferSummary[]{return (this.db.prepare(`SELECT t.uuid,t.transfer_no,t.from_outlet_uuid,fo.name from_name,t.to_outlet_uuid,to2.name to_name,t.status,t.notes,t.created_at,t.sent_at,t.received_at,COUNT(ti.id) item_count FROM stock_transfers t JOIN outlets fo ON fo.uuid=t.from_outlet_uuid JOIN outlets to2 ON to2.uuid=t.to_outlet_uuid LEFT JOIN stock_transfer_items ti ON ti.transfer_uuid=t.uuid WHERE fo.restaurant_uuid=? GROUP BY t.uuid ORDER BY t.created_at DESC`).all(restaurantUuid) as Array<{uuid:string;transfer_no:string;from_outlet_uuid:string;from_name:string;to_outlet_uuid:string;to_name:string;status:StockTransferSummary["status"];notes:string|null;created_at:string;sent_at:string|null;received_at:string|null;item_count:number}>).map(r=>({uuid:r.uuid,transferNo:r.transfer_no,fromOutletUuid:r.from_outlet_uuid,fromOutletName:r.from_name,toOutletUuid:r.to_outlet_uuid,toOutletName:r.to_name,status:r.status,notes:r.notes,createdAt:r.created_at,sentAt:r.sent_at,receivedAt:r.received_at,itemCount:r.item_count}));}
 private getTransfer(uuid:string,restaurantUuid:string){return this.db.prepare(`SELECT t.uuid,t.from_outlet_uuid fromOutletUuid,t.to_outlet_uuid toOutletUuid,t.status FROM stock_transfers t JOIN outlets o ON o.uuid=t.from_outlet_uuid WHERE t.uuid=? AND o.restaurant_uuid=?`).get(uuid,restaurantUuid) as {uuid:string;fromOutletUuid:string;toOutletUuid:string;status:string}|undefined;}
 private lines(uuid:string){return this.db.prepare(`SELECT inventory_item_uuid inventoryItemUuid,qty FROM stock_transfer_items WHERE transfer_uuid=?`).all(uuid) as Array<{inventoryItemUuid:string;qty:number}>;}
 private ensureBalances(outletUuid:string,itemUuids:string[],now:string){const stmt=this.db.prepare(`INSERT OR IGNORE INTO outlet_inventory_balances(outlet_uuid,inventory_item_uuid,on_hand,updated_at) VALUES(?,?,0,?)`);itemUuids.forEach(x=>stmt.run(outletUuid,x,now));}
}
