import { randomBytes, randomUUID } from "node:crypto";
import type Database from "better-sqlite3";
import type { CreateOnlineOrderInput, GenerateQrTokenInput, OnlineChannel, OnlineDashboard, OnlineOrder, OnlineOrderItem, QrTableToken, SaveOnlineChannelInput, UpdateOnlineOrderStatusInput } from "../../shared/contracts/online-contracts";

type ChannelRow={uuid:string;name:string;channel_type:OnlineChannel["channelType"];is_active:0|1;auto_accept:0|1};
type TokenRow={uuid:string;table_uuid:string;table_name:string;token:string;is_active:0|1};
type OrderRow={uuid:string;channel_name:string|null;external_order_id:string|null;order_type:OnlineOrder["orderType"];status:OnlineOrder["status"];customer_name:string;customer_phone:string|null;address_summary:string|null;table_name:string|null;notes:string|null;grand_total_minor:number;payment_status:OnlineOrder["paymentStatus"];received_at:string};
type ItemRow={uuid:string;item_name_snapshot:string;qty:number;unit_price_minor:number;line_total_minor:number;note:string|null};
export class OnlineRepository{
 constructor(private readonly db:Database.Database){}
 dashboard():OnlineDashboard{const orders=this.orders();return{channels:this.channels(),qrTokens:this.tokens(),orders,pendingCount:orders.filter(o=>o.status==="pending").length};}
 channels():OnlineChannel[]{return (this.db.prepare(`SELECT uuid,name,channel_type,is_active,auto_accept FROM online_channels ORDER BY name`).all() as ChannelRow[]).map(r=>({uuid:r.uuid,name:r.name,channelType:r.channel_type,isActive:r.is_active===1,autoAccept:r.auto_accept===1}));}
 tokens():QrTableToken[]{return (this.db.prepare(`SELECT q.uuid,q.table_uuid,t.name table_name,q.token,q.is_active FROM qr_table_tokens q JOIN tables t ON t.uuid=q.table_uuid ORDER BY t.name`).all() as TokenRow[]).map(r=>({uuid:r.uuid,tableUuid:r.table_uuid,tableName:r.table_name,token:r.token,orderingUrl:`https://order.mealhi5.local/t/${r.token}`,isActive:r.is_active===1}));}
 orders():OnlineOrder[]{const rows=this.db.prepare(`SELECT o.uuid,c.name channel_name,o.external_order_id,o.order_type,o.status,o.customer_name,o.customer_phone,o.address_summary,t.name table_name,o.notes,o.grand_total_minor,o.payment_status,o.received_at FROM online_orders o LEFT JOIN online_channels c ON c.uuid=o.channel_uuid LEFT JOIN tables t ON t.uuid=o.table_uuid ORDER BY CASE o.status WHEN 'pending' THEN 0 WHEN 'accepted' THEN 1 WHEN 'preparing' THEN 2 WHEN 'ready' THEN 3 ELSE 4 END,o.received_at DESC LIMIT 200`).all() as OrderRow[];const itemStmt=this.db.prepare(`SELECT uuid,item_name_snapshot,qty,unit_price_minor,line_total_minor,note FROM online_order_items WHERE online_order_uuid=? ORDER BY id`);return rows.map(r=>({...mapOrder(r),items:(itemStmt.all(r.uuid) as ItemRow[]).map(mapItem)}));}
 saveChannel(input:SaveOnlineChannelInput,now:string):OnlineChannel{const uuid=input.channelUuid??randomUUID();this.db.prepare(`INSERT INTO online_channels(uuid,name,channel_type,is_active,auto_accept,created_at,updated_at) VALUES(?,?,?,?,?,?,?) ON CONFLICT(uuid) DO UPDATE SET name=excluded.name,channel_type=excluded.channel_type,is_active=excluded.is_active,auto_accept=excluded.auto_accept,updated_at=excluded.updated_at`).run(uuid,input.name,input.channelType,input.isActive===false?0:1,input.autoAccept?1:0,now,now);const result=this.channels().find(c=>c.uuid===uuid);if(!result)throw new Error("Channel save failed.");return result;}
 generateToken(input:GenerateQrTokenInput,now:string):QrTableToken{const uuid=randomUUID();const token=randomBytes(12).toString("hex");this.db.prepare(`INSERT INTO qr_table_tokens(uuid,table_uuid,token,is_active,generated_at) VALUES(?,?,?,1,?) ON CONFLICT(table_uuid) DO UPDATE SET uuid=excluded.uuid,token=excluded.token,is_active=1,generated_at=excluded.generated_at`).run(uuid,input.tableUuid,token,now);const result=this.tokens().find(t=>t.tableUuid===input.tableUuid);if(!result)throw new Error("QR token generation failed.");return result;}
 createOrder(input:CreateOnlineOrderInput,now:string):OnlineOrder{const uuid=randomUUID();const subtotal=input.items.reduce((sum,i)=>sum+i.qty*i.unitPriceMinor,0);const autoAccept=input.channelUuid?(this.db.prepare(`SELECT auto_accept FROM online_channels WHERE uuid=?`).get(input.channelUuid) as {auto_accept:number}|undefined)?.auto_accept===1:false;const tx=this.db.transaction(()=>{this.db.prepare(`INSERT INTO online_orders(uuid,channel_uuid,external_order_id,order_type,status,customer_name,customer_phone,address_summary,table_uuid,notes,subtotal_minor,tax_minor,delivery_charge_minor,grand_total_minor,payment_status,received_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(uuid,input.channelUuid??null,input.externalOrderId??null,input.orderType,autoAccept?"accepted":"pending",input.customerName,input.customerPhone??null,input.addressSummary??null,input.tableUuid??null,input.notes??null,subtotal,0,0,subtotal,input.paymentStatus??"unpaid",now,now);const stmt=this.db.prepare(`INSERT INTO online_order_items(uuid,online_order_uuid,product_uuid,item_name_snapshot,qty,unit_price_minor,line_total_minor,modifiers_json,note) VALUES(?,?,?,?,?,?,?,?,?)`);for(const item of input.items)stmt.run(randomUUID(),uuid,item.productUuid??null,item.itemName,item.qty,item.unitPriceMinor,item.qty*item.unitPriceMinor,"[]",item.note??null);});tx();const result=this.orders().find(o=>o.uuid===uuid);if(!result)throw new Error("Online order creation failed.");return result;}
 updateStatus(input:UpdateOnlineOrderStatusInput,now:string):OnlineOrder{this.db.prepare(`UPDATE online_orders SET status=?,updated_at=? WHERE uuid=?`).run(input.status,now,input.orderUuid);const result=this.orders().find(o=>o.uuid===input.orderUuid);if(!result)throw Object.assign(new Error("Online order not found."),{code:"NOT_FOUND"});return result;}
}
function mapOrder(r:OrderRow):Omit<OnlineOrder,"items">{return{uuid:r.uuid,channelName:r.channel_name,externalOrderId:r.external_order_id,orderType:r.order_type,status:r.status,customerName:r.customer_name,customerPhone:r.customer_phone,addressSummary:r.address_summary,tableName:r.table_name,notes:r.notes,grandTotalMinor:r.grand_total_minor,paymentStatus:r.payment_status,receivedAt:r.received_at};}
function mapItem(r:ItemRow):OnlineOrderItem{return{uuid:r.uuid,itemName:r.item_name_snapshot,qty:r.qty,unitPriceMinor:r.unit_price_minor,lineTotalMinor:r.line_total_minor,note:r.note};}
