import { randomUUID } from "node:crypto";
import type Database from "better-sqlite3";
import type { PrintJobSummary, PrinterProfile, PrinterRoute, SavePrinterInput, SavePrinterRouteInput } from "../../shared/contracts/printer-contracts";
type Row={uuid:string;name:string;role:PrinterProfile["role"];connection_type:PrinterProfile["connectionType"];host:string|null;port:number|null;device_path:string|null;paper_width_mm:58|80;characters_per_line:number;auto_cut:number;open_cash_drawer:number;is_default:number;is_active:number;created_at:string;updated_at:string};
export class PrinterRepository{
 constructor(private readonly db:Database.Database){}
 list():PrinterProfile[]{return (this.db.prepare("SELECT * FROM printer_profiles ORDER BY is_default DESC, role, name").all() as Row[]).map(mapPrinter);}
 get(uuid:string):PrinterProfile|null{const r=this.db.prepare("SELECT * FROM printer_profiles WHERE uuid=?").get(uuid) as Row|undefined;return r?mapPrinter(r):null;}
 getDefault(role:PrinterProfile["role"]):PrinterProfile|null{const r=this.db.prepare("SELECT * FROM printer_profiles WHERE role=? AND is_active=1 ORDER BY is_default DESC,id LIMIT 1").get(role) as Row|undefined;return r?mapPrinter(r):null;}
 save(input:SavePrinterInput):PrinterProfile{const now=new Date().toISOString(),uuid=input.uuid??randomUUID();if(input.isDefault)this.db.prepare("UPDATE printer_profiles SET is_default=0 WHERE role=?").run(input.role);this.db.prepare(`INSERT INTO printer_profiles (uuid,name,role,connection_type,host,port,device_path,paper_width_mm,characters_per_line,auto_cut,open_cash_drawer,is_default,is_active,created_at,updated_at)
 VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(uuid) DO UPDATE SET name=excluded.name,role=excluded.role,connection_type=excluded.connection_type,host=excluded.host,port=excluded.port,device_path=excluded.device_path,paper_width_mm=excluded.paper_width_mm,characters_per_line=excluded.characters_per_line,auto_cut=excluded.auto_cut,open_cash_drawer=excluded.open_cash_drawer,is_default=excluded.is_default,is_active=excluded.is_active,updated_at=excluded.updated_at`).run(uuid,input.name,input.role,input.connectionType,input.host,input.port,input.devicePath,input.paperWidthMm,input.charactersPerLine,input.autoCut?1:0,input.openCashDrawer?1:0,input.isDefault?1:0,input.isActive?1:0,now,now);return this.get(uuid)!;}
 routes():PrinterRoute[]{return (this.db.prepare("SELECT uuid,document_type,category_uuid,printer_uuid,priority FROM printer_routes ORDER BY priority DESC,id").all() as any[]).map(r=>({uuid:r.uuid,documentType:r.document_type,categoryUuid:r.category_uuid,printerUuid:r.printer_uuid,priority:r.priority}));}
 saveRoute(i:SavePrinterRouteInput):PrinterRoute{const uuid=i.uuid??randomUUID(),now=new Date().toISOString();this.db.prepare(`INSERT INTO printer_routes (uuid,document_type,category_uuid,printer_uuid,priority,created_at,updated_at) VALUES (?,?,?,?,?,?,?) ON CONFLICT(uuid) DO UPDATE SET document_type=excluded.document_type,category_uuid=excluded.category_uuid,printer_uuid=excluded.printer_uuid,priority=excluded.priority,updated_at=excluded.updated_at`).run(uuid,i.documentType,i.categoryUuid,i.printerUuid,i.priority,now,now);return this.routes().find(x=>x.uuid===uuid)!;}
 assignJob(jobUuid:string,printerUuid:string,now:string){this.db.prepare("UPDATE print_jobs SET printer_uuid=?,updated_at=? WHERE uuid=?").run(printerUuid,now,jobUuid);}
 createJob(input:{documentType:"receipt"|"kot";documentUuid:string;printerUuid:string|null;copyType:"original"|"duplicate";jobKind:"print"|"test"|"drawer";payload:unknown;userUuid:string}){const uuid=randomUUID(),now=new Date().toISOString();this.db.prepare(`INSERT INTO print_jobs (uuid,document_type,document_uuid,status,copy_type,payload_json,attempts,created_by_user_uuid,created_at,printer_uuid,job_kind,updated_at) VALUES (?,?,?,'pending',?,?,0,?,?,?,?,?)`).run(uuid,input.documentType,input.documentUuid,input.copyType,JSON.stringify(input.payload),input.userUuid,now,input.printerUuid,input.jobKind,now);return uuid;}
 pending(limit=20):Array<PrintJobSummary&{payloadJson:string}>{return this.jobs(`WHERE pj.status IN ('pending','failed') AND pj.cancelled_at IS NULL AND (pj.next_attempt_at IS NULL OR pj.next_attempt_at<=?)`,[new Date().toISOString(),limit]);}
 listJobs(limit=100):PrintJobSummary[]{return this.jobs("",[limit]).map(({payloadJson,...x})=>x);}
 private jobs(where:string,args:any[]):Array<PrintJobSummary&{payloadJson:string}>{const sql=`SELECT pj.*,pp.name printer_name FROM print_jobs pj LEFT JOIN printer_profiles pp ON pp.uuid=pj.printer_uuid ${where} ORDER BY pj.created_at DESC LIMIT ?`;return (this.db.prepare(sql).all(...args) as any[]).map(r=>({uuid:r.uuid,documentType:r.document_type,documentUuid:r.document_uuid,printerUuid:r.printer_uuid,printerName:r.printer_name,status:r.status,copyType:r.copy_type,jobKind:r.job_kind??'print',attempts:r.attempts,errorMessage:r.error_message,createdAt:r.created_at,printedAt:r.printed_at,cancelledAt:r.cancelled_at,payloadJson:r.payload_json}));}
 markPrinted(uuid:string){const now=new Date().toISOString();this.db.prepare("UPDATE print_jobs SET status='printed',attempts=attempts+1,error_message=NULL,printed_at=?,updated_at=? WHERE uuid=?").run(now,now,uuid);}
 markFailed(uuid:string,message:string){const now=new Date(),next=new Date(now.getTime()+30000).toISOString();this.db.prepare("UPDATE print_jobs SET status='failed',attempts=attempts+1,error_message=?,next_attempt_at=?,updated_at=? WHERE uuid=?").run(message.slice(0,500),next,now.toISOString(),uuid);}
 retry(uuid:string){const now=new Date().toISOString();this.db.prepare("UPDATE print_jobs SET status='pending',error_message=NULL,next_attempt_at=NULL,updated_at=? WHERE uuid=?").run(now,uuid);}
}
function mapPrinter(r:Row):PrinterProfile{return{uuid:r.uuid,name:r.name,role:r.role,connectionType:r.connection_type,host:r.host,port:r.port,devicePath:r.device_path,paperWidthMm:r.paper_width_mm,charactersPerLine:r.characters_per_line,autoCut:!!r.auto_cut,openCashDrawer:!!r.open_cash_drawer,isDefault:!!r.is_default,isActive:!!r.is_active,createdAt:r.created_at,updatedAt:r.updated_at};}
